package org.enthusia;

import android.util.TypedValue;

/**
 * Created by Yogesh on 9/23/2017.
 */

public class Constants {
    public final static int EVENTS_FRAGMENT = 0;
    public final static int CUP_FRAGMENT = 1;
    public final static int ABOUT_US_FRAGMENT = 2;
    public final static int FEED_FRAGMENT = 3;
    public static final int SPONSORS_FRAGMENT = 4;
    public static final int COMMITTEE_FRAGMENT = 24;
    public static final int DH_FRAGMENT = 45;



    public static String[] partners = new String[] {
            "Powered By",
            "",
            "Co-Powered By",
            "",
            "Exclusive Partners",
            "",
            "Adventure Gear Partner",
            "",
            "",
            "",
            "Audio Partner",
            "Bakery Partner",
            "Beverage Partner",
            "Confectionery Partner",
            "Cyclothon Partner",
            "Donut Partner",
            "Energy Bar Partner",
            "Fitness Partner",
            "Football Club Partner",
            "Fruit Drink Partner",
            "NGO Partner",
            "Gadget Partner",
            "Discount Partner",
            "Hair and Style Partner",
            "Health Drink Partner",
            "Indulgence Partner",
            "Knowledge Partner",
            "Merchandise Partner",
            "Mocktail Partner",
            "",
            "",
            "",
            "Multiplex Partner",
            "Munching Partner",
            "Pain Relief Partner",
            "Performance Partner",
            "Photography Partner",
            "Radio Partner",
            "Refreshment Partner",
            "SMS partner",
            "Snack Partner",
            "Sport Partner",
            "Student Partner",
            "Thrill Partner",
            "Youth Partner",
            "Gifting Partner",
            "Musical Partner",
            "Restaurant partner",
            "Lounge Partner",
            "Music Institute Partner",
            "Apparel Partner",
            "Online Media Partner",
            "Media Partners",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Associate Partners",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
    };





    public static String[] links = new String[]{
            "https://www.facebook.com/ZootEntertainment/",
            "",
            "http://www.paragmilkfoods.com/",
            "",
            "Exclusive Sponsors",
            "",
            "",
            "",
            "https://www.outdoortravelgear.com/",
            "https://www.outdoortravelgear.com/",
            "http://www.muveacoustics.com/",
            "https://www.zomato.com/mumbai/gluttony-marol",
            "http://tranquini.com/",
            "http://www.mapro.com/",
            "https://www.facebook.com/Bharat-Cycle-228572413878206/",
            "http://www.madoverdonuts.com/",
            "http://mojobars.com/",
            "https://powerhousegym.com/",
            "http://www.mumbaicityfc.com/",
            "http://www.ilovemogumogu.com/mogumogu.html",
            "http://robinhoodarmy.com",
            "https://www.gizmobaba.com/",
            "http://www.zinqcard.com/",
            "http://envisalon.in/",
            "http://superfit.asia/shop/beverages/mojoco/",
            "http://sukhdata.webcloudinfotech.com/",
            "http://www.studyin-uk.in/",
            "http://www.printiconic.com/",
            "",
            "",
            "http://www.mexerbeverages.com/index.html",
            "http://www.mexerbeverages.com/index.html",
            "https://www.inoxmovies.com/",
            "https://tonggarden.com.sg/",
            "http://www.relispray.com/",
            "https://www.motul.com/",
            "http://camzia.in/",
            "https://www.facebook.com/fmgoldmumbai/",
            "http://spraymintt.com/",
            "https://www.textguru.in/",
            "http://www.balajiwafers.com/",
            "https://www.sportobuddy.com/",
            "https://frapp.in/",
            "http://www.noescape.in/",
            "http://www.youthincmag.com/",
            "",
            "",
            "http://neelamepunjab.suncorenergycentreeasttower.club/",
            "",
            "",
            "",
            "http://topyaps.com/",
            "Media Partner",
            "",
            "https://maharashtratimes.indiatimes.com/",
            "https://tenfizz.com/",
            "http://festpav.com/",
            "https://jammag.com/",
            "",
            "http://www.afternoondc.in/",
            "Associate Sponsor",
            "",
            "https://www.instagram.com/thepaperdolphin/",
            "https://www.mcdonaldsindia.com/",
            "http://www.careerlauncher.com/",
            "http://greatescape.co.in/",
            "http://aberrantwanderers.com",
            "http://www.whatthefun.co.in/",
            "https://www.hashtagstore.in/",
            "http://bachelorrs.com/",
            "http://thetuckbox.com/",
            "http://www.polestarbags.com/",
            "",
            "https://www.wisholize.com/",
            "https://www.wristbandwala.com/",
            "http://www.bawajiwafers.com/",
            "http://www.herbarioindia.com/",
            "https://www.federalbank.co.in/",
            "http://www.gonemad.co.in/",
            "http://www.domadia.com/",
            "http://www.dukesindia.com/waffers.html",
            "https://www.justdial.com/Mumbai/Alankar-Eye-Care-Opposite-Shree-Sagar-Hotel-Borivali-West/022PXX22-XX22-110709130312-I5I7_BZDET",
            "https://www.facebook.com/thebombayfries/",
            "https://www.kitgenie.com/",
            "http://www.poshtick.com/",
            "https://www.facebook.com/BomberryMumbai/",
            "http://www.dinshaws.co.in/",
            "http://www.indiarushsoccer.com/",
            "https://www.facebook.com/PlayOnArena/",
            "https://www.amazon.in/Watches-Foce/s?ie=UTF8&field-brandtextbin=Foce&page=1&rh=n%3A1350387031",
            "http://www.koldplay.in/",
            "https://www.facebook.com/undergroundcomedyinc/",
            "http://www.dreamsportsfields.com/",
            "http://zevic.in/",
            "https://bootees.in/",
            ""
    };



    public static int[] imageIds = new int[]{
            R.drawable.zoot,
            1,
            R.drawable.slurp,
            1,
            0,
            1,
            0,
            1,
            R.drawable.outdoortravelgear,
            R.drawable.quipco,
            R.drawable.muve,
            R.drawable.gluttony,
            R.drawable.tranquini,
            R.drawable.mapro,
            R.drawable.bharatcycle,
            R.drawable.mod,
            R.drawable.mojobar,
            R.drawable.powerhouse,
            R.drawable.mcfc,
            R.drawable.mogumogu,
            R.drawable.robinhoodarmy,
            R.drawable.gizmobaba,
            R.drawable.zinq,
            R.drawable.envi,
            R.drawable.mojoco,
            R.drawable.sukhdata,
            R.drawable.siuk,
            R.drawable.printiconic,
            0,
            1,
            R.drawable.mixtale,
            R.drawable.spicetale,
            R.drawable.inox,
            R.drawable.tonggarden,
            R.drawable.relispray,
            R.drawable.motul,
            R.drawable.camzia,
            R.drawable.fmgold,
            R.drawable.spraymintt,
            R.drawable.textguru,
            R.drawable.balaji,
            R.drawable.sportobuddy,
            R.drawable.frapp,
            R.drawable.noescape,
            R.drawable.youthinc,
            R.drawable.theknottythreads,
            R.drawable.guitarstudio,
            R.drawable.neelam,
            R.drawable.whiterun,
            R.drawable.ygp,
            R.drawable.barcode,
            R.drawable.topyaps,
            0,
            1,
            R.drawable.maharashtratimes,
            R.drawable.ten,
            R.drawable.festpav,
            R.drawable.jam,
            R.drawable.corporateindia,
            R.drawable.afternoon,
            0,
            1,
            R.drawable.paperdolphin,
            R.drawable.mcdonalds,
            R.drawable.careerlauncher,
            R.drawable.greatescape,
            R.drawable.aberrant,
            R.drawable.wtfun,
            R.drawable.hashtag,
            R.drawable.bachelorrs,
            R.drawable.tuckbox,
            R.drawable.polestar,
            R.drawable.spandan,
            R.drawable.wisholize,
            R.drawable.wristbandwala,
            R.drawable.bawaji,
            R.drawable.glamour,
            R.drawable.federalbank,
            R.drawable.gonemad,
            R.drawable.dalielectronics,
            R.drawable.dukes,
            R.drawable.alankareyecare,
            R.drawable.thebombayfries,
            R.drawable.kitgenie,
            R.drawable.poshtick,
            R.drawable.bomberry,
            R.drawable.dinshaws,
            R.drawable.indiarushsc,
            R.drawable.playonarena,
            R.drawable.foce,
            R.drawable.koldplay,
            R.drawable.underground,
            R.drawable.dsf,
            R.drawable.zevic,
            R.drawable.bootees,
            1
    };

    public static String news = "";
    public static String leaderboard = "";
}
